import '../models/product_sku.dart';
import '../models/category_model.dart';
import '../models/stock_in_order.dart';
import '../models/stock_out_order.dart';
import '../models/cycle_count_session.dart';

class SeedData {
  static List<CategoryModel> get categories => [
    const CategoryModel(
      id: 'CAT-ELC',
      code: 'ELC',
      name: 'Điện tử & Công nghệ',
      colorHex: 0xFF1E40AF, // Deep Indigo
      description: 'Thiết bị điện tử, điện thoại, máy tính và phụ kiện',
    ),
    const CategoryModel(
      id: 'CAT-HOM',
      code: 'HOM',
      name: 'Gia dụng & Đời sống',
      colorHex: 0xFF0D9488, // Teal
      description: 'Thiết bị nhà bếp, quạt mát, máy lọc nước',
    ),
    const CategoryModel(
      id: 'CAT-FOD',
      code: 'FOD',
      name: 'Thực phẩm & Tiêu dùng',
      colorHex: 0xFFF59E0B, // Amber
      description: 'Đồ hộp, sữa hạt, bánh kẹo, thực phẩm khô',
    ),
    const CategoryModel(
      id: 'CAT-CHM',
      code: 'CHM',
      name: 'Hóa mỹ phẩm & Tẩy rửa',
      colorHex: 0xFF8B5CF6, // Purple
      description: 'Nước giặt, xà phòng, dầu gội, nước lau sàn',
    ),
  ];

  static List<ProductSKU> get products => [
    // Nhóm A: Doanh thu cao, giá trị lớn
    ProductSKU(
      id: 'prod-001',
      skuCode: 'SKU-ELC-IP15',
      barcode: '8938501230012',
      name: 'Điện thoại iPhone 15 Pro Max 256GB',
      categoryId: 'CAT-ELC',
      categoryName: 'Điện tử & Công nghệ',
      costPrice: 26500000,
      sellingPrice: 29990000,
      currentStock: 42,
      minSafetyStock: 15,
      maxStock: 80,
      locationTag: 'KHO-A-KAY-01',
      unit: 'Chiếc',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
    ),
    ProductSKU(
      id: 'prod-002',
      skuCode: 'SKU-ELC-TV65',
      barcode: '8938501230029',
      name: 'Smart Tivi Sony 4K 65 inch Bravia',
      categoryId: 'CAT-ELC',
      categoryName: 'Điện tử & Công nghệ',
      costPrice: 15200000,
      sellingPrice: 18490000,
      currentStock: 18,
      minSafetyStock: 8,
      maxStock: 40,
      locationTag: 'KHO-A-KAY-03',
      unit: 'Chiếc',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 3)),
      createdAt: DateTime.now().subtract(const Duration(days: 100)),
    ),
    ProductSKU(
      id: 'prod-003',
      skuCode: 'SKU-ELC-LAPDELL',
      barcode: '8938501230036',
      name: 'Laptop Dell XPS 13 Plus Core i7',
      categoryId: 'CAT-ELC',
      categoryName: 'Điện tử & Công nghệ',
      costPrice: 32000000,
      sellingPrice: 36500000,
      currentStock: 12,
      minSafetyStock: 10,
      maxStock: 30,
      locationTag: 'KHO-A-KAY-02',
      unit: 'Chiếc',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),

    // Nhóm B: Gia dụng & Bếp
    ProductSKU(
      id: 'prod-004',
      skuCode: 'SKU-HOM-NOICHIEN',
      barcode: '8938501230043',
      name: 'Nồi chiên không dầu Philips HD9280 6.2L',
      categoryId: 'CAT-HOM',
      categoryName: 'Gia dụng & Đời sống',
      costPrice: 2150000,
      sellingPrice: 2890000,
      currentStock: 65,
      minSafetyStock: 25,
      maxStock: 120,
      locationTag: 'KHO-B-RACK-01',
      unit: 'Cái',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 4)),
      createdAt: DateTime.now().subtract(const Duration(days: 150)),
    ),
    ProductSKU(
      id: 'prod-005',
      skuCode: 'SKU-HOM-ROBOT',
      barcode: '8938501230050',
      name: 'Robot hút bụi lau nhà Xiaomi X10 Plus',
      categoryId: 'CAT-HOM',
      categoryName: 'Gia dụng & Đời sống',
      costPrice: 7800000,
      sellingPrice: 9990000,
      currentStock: 22,
      minSafetyStock: 10,
      maxStock: 50,
      locationTag: 'KHO-B-RACK-02',
      unit: 'Bộ',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 6)),
      createdAt: DateTime.now().subtract(const Duration(days: 110)),
    ),
    ProductSKU(
      id: 'prod-006',
      skuCode: 'SKU-HOM-LOCNUOC',
      barcode: '8938501230067',
      name: 'Máy lọc nước RO Kangaroo 10 lõi Hydro',
      categoryId: 'CAT-HOM',
      categoryName: 'Gia dụng & Đời sống',
      costPrice: 4200000,
      sellingPrice: 5490000,
      currentStock: 8, // Low stock alert! (min is 12)
      minSafetyStock: 12,
      maxStock: 40,
      locationTag: 'KHO-B-RACK-03',
      unit: 'Bộ',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 5)),
      createdAt: DateTime.now().subtract(const Duration(days: 80)),
    ),

    // Nhóm C & Thực phẩm có HSD (FEFO)
    ProductSKU(
      id: 'prod-007',
      skuCode: 'SKU-FOD-SUAHAT',
      barcode: '8938501230074',
      name: 'Sữa Hạt Óc Chó Hạnh Nhân TH True Nut (Thùng 24 hộp)',
      categoryId: 'CAT-FOD',
      categoryName: 'Thực phẩm & Tiêu dùng',
      costPrice: 280000,
      sellingPrice: 350000,
      currentStock: 140,
      minSafetyStock: 50,
      maxStock: 300,
      locationTag: 'KHO-C-PALLET-01',
      unit: 'Thùng',
      expiryDate: DateTime.now().add(const Duration(days: 22)), // Expiring soon (< 30 days)!
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 160)),
    ),
    ProductSKU(
      id: 'prod-008',
      skuCode: 'SKU-FOD-DAUAN',
      barcode: '8938501230081',
      name: 'Dầu ăn đậu nành Simply 5L nguyên chất',
      categoryId: 'CAT-FOD',
      categoryName: 'Thực phẩm & Tiêu dùng',
      costPrice: 215000,
      sellingPrice: 265000,
      currentStock: 95,
      minSafetyStock: 40,
      maxStock: 250,
      locationTag: 'KHO-C-PALLET-02',
      unit: 'Can',
      expiryDate: DateTime.now().add(const Duration(days: 240)),
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 130)),
    ),
    ProductSKU(
      id: 'prod-009',
      skuCode: 'SKU-FOD-BANHQUY',
      barcode: '8938501230098',
      name: 'Bánh Quy Bơ Pháp Danisa Hoàng Gia 681g',
      categoryId: 'CAT-FOD',
      categoryName: 'Thực phẩm & Tiêu dùng',
      costPrice: 145000,
      sellingPrice: 195000,
      currentStock: 5, // Low stock alert!
      minSafetyStock: 30,
      maxStock: 200,
      locationTag: 'KHO-C-PALLET-03',
      unit: 'Hộp',
      expiryDate: DateTime.now().subtract(const Duration(days: 5)), // Expired!
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 45)),
      createdAt: DateTime.now().subtract(const Duration(days: 200)),
    ),

    // Hóa mỹ phẩm
    ProductSKU(
      id: 'prod-010',
      skuCode: 'SKU-CHM-NUOCGIAT',
      barcode: '8938501230104',
      name: 'Nước Giặt Ariel Cửa Trước Hương Ban Mai 3.8kg',
      categoryId: 'CAT-CHM',
      categoryName: 'Hóa mỹ phẩm & Tẩy rửa',
      costPrice: 175000,
      sellingPrice: 235000,
      currentStock: 180,
      minSafetyStock: 60,
      maxStock: 400,
      locationTag: 'KHO-D-BIN-01',
      unit: 'Túi',
      expiryDate: DateTime.now().add(const Duration(days: 450)),
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 140)),
    ),
    ProductSKU(
      id: 'prod-011',
      skuCode: 'SKU-CHM-DAUGOI',
      barcode: '8938501230111',
      name: 'Dầu Gội Head & Shoulders Bạc Hà Mát Lạnh 850ml',
      categoryId: 'CAT-CHM',
      categoryName: 'Hóa mỹ phẩm & Tẩy rửa',
      costPrice: 155000,
      sellingPrice: 210000,
      currentStock: 85,
      minSafetyStock: 30,
      maxStock: 200,
      locationTag: 'KHO-D-BIN-02',
      unit: 'Chai',
      expiryDate: DateTime.now().add(const Duration(days: 500)),
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 3)),
      createdAt: DateTime.now().subtract(const Duration(days: 100)),
    ),

    // Phụ kiện & Hàng tồn đọng lâu ngày (Dead Stock)
    ProductSKU(
      id: 'prod-012',
      skuCode: 'SKU-ELC-CAPSAC',
      barcode: '8938501230128',
      name: 'Cáp sạc Baseus Type-C to Lightning PD 20W',
      categoryId: 'CAT-ELC',
      categoryName: 'Điện tử & Công nghệ',
      costPrice: 65000,
      sellingPrice: 120000,
      currentStock: 220,
      minSafetyStock: 50,
      maxStock: 500,
      locationTag: 'KHO-A-KAY-04',
      unit: 'Sợi',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    ProductSKU(
      id: 'prod-013',
      skuCode: 'SKU-HOM-QUATBAN',
      barcode: '8938501230135',
      name: 'Quạt bàn Senko B102 sải cánh 20cm (Tồn cũ)',
      categoryId: 'CAT-HOM',
      categoryName: 'Gia dụng & Đời sống',
      costPrice: 160000,
      sellingPrice: 220000,
      currentStock: 38,
      minSafetyStock: 10,
      maxStock: 60,
      locationTag: 'KHO-B-RACK-05',
      unit: 'Cái',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 78)), // Dead Stock! > 60 days
      createdAt: DateTime.now().subtract(const Duration(days: 180)),
    ),
    ProductSKU(
      id: 'prod-014',
      skuCode: 'SKU-ELC-TAINGHEOLD',
      barcode: '8938501230142',
      name: 'Tai nghe Bluetooth mini Remax RB-T9 (Hàng xả kho)',
      categoryId: 'CAT-ELC',
      categoryName: 'Điện tử & Công nghệ',
      costPrice: 85000,
      sellingPrice: 130000,
      currentStock: 55,
      minSafetyStock: 15,
      maxStock: 100,
      locationTag: 'KHO-A-KAY-05',
      unit: 'Chiếc',
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 92)), // Dead Stock!
      createdAt: DateTime.now().subtract(const Duration(days: 210)),
    ),
    ProductSKU(
      id: 'prod-015',
      skuCode: 'SKU-CHM-XAPHONG',
      barcode: '8938501230159',
      name: 'Xà Bông Cục Lifebuoy Bảo Vệ Khỏi Vi Khuẩn 90g',
      categoryId: 'CAT-CHM',
      categoryName: 'Hóa mỹ phẩm & Tẩy rửa',
      costPrice: 11000,
      sellingPrice: 16000,
      currentStock: 320,
      minSafetyStock: 100,
      maxStock: 600,
      locationTag: 'KHO-D-BIN-04',
      unit: 'Bánh',
      expiryDate: DateTime.now().add(const Duration(days: 600)),
      lastStockOutDate: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 70)),
    ),
  ];

  static List<StockInOrder> get stockInOrders => [
    StockInOrder(
      id: 'in-001',
      orderNumber: 'PNK-2026-0819',
      supplierName: 'Apple Distribution Vietnam',
      supplierPhone: '028 3822 9999',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      createdBy: 'Nguyễn Văn Quản',
      notes: 'Nhập lô hàng chính hãng lô 3 đợt quý 3',
      items: const [
        StockInItem(
          skuId: 'prod-001',
          skuCode: 'SKU-ELC-IP15',
          skuName: 'Điện thoại iPhone 15 Pro Max 256GB',
          barcode: '8938501230012',
          quantity: 20,
          unitPrice: 26500000,
          locationTag: 'KHO-A-KAY-01',
          currentCostBefore: 26500000,
          macAfter: 26500000,
        ),
        StockInItem(
          skuId: 'prod-012',
          skuCode: 'SKU-ELC-CAPSAC',
          skuName: 'Cáp sạc Baseus Type-C to Lightning PD 20W',
          barcode: '8938501230128',
          quantity: 100,
          unitPrice: 65000,
          locationTag: 'KHO-A-KAY-04',
          currentCostBefore: 65000,
          macAfter: 65000,
        ),
      ],
    ),
    StockInOrder(
      id: 'in-002',
      orderNumber: 'PNK-2026-0822',
      supplierName: 'Tập đoàn Masan Consumer',
      supplierPhone: '028 6255 5660',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      createdBy: 'Trần Thị Kho',
      notes: 'Nhập bổ sung thực phẩm và dầu ăn Simply',
      items: [
        StockInItem(
          skuId: 'prod-008',
          skuCode: 'SKU-FOD-DAUAN',
          skuName: 'Dầu ăn đậu nành Simply 5L nguyên chất',
          barcode: '8938501230081',
          quantity: 50,
          unitPrice: 215000,
          locationTag: 'KHO-C-PALLET-02',
          currentCostBefore: 212000,
          macAfter: 215000,
          expiryDate: DateTime.now().add(const Duration(days: 240)),
        ),
      ],
    ),
  ];

  static List<StockOutOrder> get stockOutOrders => [
    StockOutOrder(
      id: 'out-001',
      orderNumber: 'PXK-2026-0901',
      type: StockOutType.wholesale,
      receiverName: 'Đại lý Điện máy Chợ Lớn Miền Đông',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      createdBy: 'Nguyễn Văn Quản',
      notes: 'Đơn sỉ hợp đồng số HD-7732',
      items: const [
        StockOutItem(
          skuId: 'prod-001',
          skuCode: 'SKU-ELC-IP15',
          skuName: 'Điện thoại iPhone 15 Pro Max 256GB',
          barcode: '8938501230012',
          quantity: 5,
          unitPrice: 28800000,
          costPrice: 26500000,
        ),
        StockOutItem(
          skuId: 'prod-004',
          skuCode: 'SKU-HOM-NOICHIEN',
          skuName: 'Nồi chiên không dầu Philips HD9280 6.2L',
          barcode: '8938501230043',
          quantity: 10,
          unitPrice: 2650000,
          costPrice: 2150000,
        ),
      ],
    ),
    StockOutOrder(
      id: 'out-002',
      orderNumber: 'PXK-2026-0902',
      type: StockOutType.transfer,
      receiverName: 'Kho Chi nhánh Quận 7 (TP.HCM)',
      destinationBranch: 'Kho Chi nhánh Quận 7 - 120 Nguyễn Thị Thập',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      createdBy: 'Trần Thị Kho',
      notes: 'Điều chuyển cân đối hàng tồn cho chi nhánh Q7',
      items: const [
        StockOutItem(
          skuId: 'prod-010',
          skuCode: 'SKU-CHM-NUOCGIAT',
          skuName: 'Nước Giặt Ariel Cửa Trước Hương Ban Mai 3.8kg',
          barcode: '8938501230104',
          quantity: 30,
          unitPrice: 175000,
          costPrice: 175000,
        ),
        StockOutItem(
          skuId: 'prod-015',
          skuCode: 'SKU-CHM-XAPHONG',
          skuName: 'Xà Bông Cục Lifebuoy Bảo Vệ Khỏi Vi Khuẩn 90g',
          barcode: '8938501230159',
          quantity: 80,
          unitPrice: 11000,
          costPrice: 11000,
        ),
      ],
    ),
    StockOutOrder(
      id: 'out-003',
      orderNumber: 'PXK-2026-0903',
      type: StockOutType.retail,
      receiverName: 'Khách lẻ - Hoàng Minh Tuấn',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      createdBy: 'Lê Thu Trang',
      items: const [
        StockOutItem(
          skuId: 'prod-005',
          skuCode: 'SKU-HOM-ROBOT',
          skuName: 'Robot hút bụi lau nhà Xiaomi X10 Plus',
          barcode: '8938501230050',
          quantity: 1,
          unitPrice: 9990000,
          costPrice: 7800000,
        ),
      ],
    ),
  ];

  static List<CycleCountSession> get cycleCounts => [
    CycleCountSession(
      id: 'cc-001',
      sessionCode: 'KK-2026-Q3-01',
      title: 'Kiểm kê định kỳ Khu vực Điện tử Kệ A',
      scope: 'Khu Vực Kệ A (Điện máy & Công nghệ)',
      status: CycleCountStatus.inProgress,
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      auditorName: 'Nguyễn Văn Quản',
      items: [
        CycleCountItem(
          skuId: 'prod-001',
          skuCode: 'SKU-ELC-IP15',
          skuName: 'Điện thoại iPhone 15 Pro Max 256GB',
          barcode: '8938501230012',
          locationTag: 'KHO-A-KAY-01',
          bookStock: 42,
          physicalCount: 42,
          costPrice: 26500000,
          isAudited: true, // Khớp
        ),
        CycleCountItem(
          skuId: 'prod-002',
          skuCode: 'SKU-ELC-TV65',
          skuName: 'Smart Tivi Sony 4K 65 inch Bravia',
          barcode: '8938501230029',
          locationTag: 'KHO-A-KAY-03',
          bookStock: 18,
          physicalCount: 17, // Thiếu 1 chiếc
          costPrice: 15200000,
          isAudited: true,
        ),
        CycleCountItem(
          skuId: 'prod-003',
          skuCode: 'SKU-ELC-LAPDELL',
          barcode: '8938501230036',
          skuName: 'Laptop Dell XPS 13 Plus Core i7',
          locationTag: 'KHO-A-KAY-02',
          bookStock: 12,
          physicalCount: 13, // Thừa 1 chiếc
          costPrice: 32000000,
          isAudited: true,
        ),
        CycleCountItem(
          skuId: 'prod-012',
          skuCode: 'SKU-ELC-CAPSAC',
          barcode: '8938501230128',
          skuName: 'Cáp sạc Baseus Type-C to Lightning PD 20W',
          locationTag: 'KHO-A-KAY-04',
          bookStock: 220,
          physicalCount: 0,
          costPrice: 65000,
          isAudited: false, // Chưa kiểm
        ),
      ],
    ),
  ];
}
